
import * as React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Gavel, Mail, Globe } from 'lucide-react';

const TermsPage: React.FunctionComponent = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#0b0e14] text-white font-sans selection:bg-noble-blue/30">
      <nav className="fixed top-0 w-full z-50 bg-[#0b0e14]/80 backdrop-blur-xl border-b border-white/5 px-4 md:px-8 h-20 flex items-center justify-between">
        <div className="flex items-center gap-3 cursor-pointer" onClick={() => navigate('/')}>
          <div className="w-10 h-10 bg-noble-blue rounded-xl flex items-center justify-center">
            <Globe className="w-6 h-6 text-white" />
          </div>
          <span className="font-['Montserrat'] font-extrabold text-xl tracking-tight uppercase">Terms of Service</span>
        </div>
        <button onClick={() => navigate('/')} className="flex items-center gap-2 text-sm font-medium text-slate-400 hover:text-white">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
      </nav>

      <main className="max-w-4xl mx-auto px-6 pt-40 pb-32">
        <div className="prose prose-invert max-w-none space-y-10">
          <header className="border-b border-slate-800 pb-12">
            <h1 className="text-4xl md:text-6xl font-extrabold font-display mb-4">Terms of Service: Noble Clarity Engine</h1>
            <p className="text-slate-400">Effective Date: December 30, 2025</p>
          </header>

          <section className="space-y-4">
            <p className="text-slate-400 leading-relaxed">
              Please read these Terms of Service (“Terms”) carefully. By accessing or using the Noble Clarity Engine (the “Platform”), you agree to be bound by these Terms. If you are entering into these Terms on behalf of a business entity (SME), you represent that you have the authority to bind that entity.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">1. Description of Service</h2>
            <p className="text-slate-400 leading-relaxed">
              Noble World provides a React-based financial intelligence dashboard that processes Business Financial Data to offer:
            </p>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li>Real-time business health monitoring.</li>
              <li>Cash flow forecasting and scenario planning.</li>
              <li><strong>AI Coaching:</strong> Automated insights and Text-to-Speech (TTS) responses generated by our Hybrid Intelligence Layer (Google Gemini & OpenAI).</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">2. Eligibility and Account Registration</h2>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li><strong>Business Use:</strong> The Platform is intended for use by Small and Medium Enterprises (SMEs) and professional business owners. It is not intended for personal, family, or household use.</li>
              <li><strong>Security:</strong> Authentication is managed via Google Firebase. You are responsible for maintaining the confidentiality of your credentials. Any activity occurring under your account is your responsibility.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">3. Subscription, Billing, and Payments</h2>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li><strong>Payment Processors:</strong> Payments are processed through Paystack and Flutterwave. By subscribing, you agree to their respective terms and PCI-DSS compliant handling of your financial instruments.</li>
              <li><strong>Recurring Billing:</strong> Unless otherwise stated, subscriptions are billed in advance on a recurring basis.</li>
              <li><strong>Refund Policy:</strong> Subscriptions are non-refundable except where required by law.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">4. Intellectual Property</h2>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li><strong>The Platform:</strong> Noble World owns all rights, title, and interest in the Noble Clarity Engine, including the React architecture, proprietary algorithms, UI/UX design, and the "Noble World" brand.</li>
              <li><strong>Your Data:</strong> You retain 100% ownership of the Business Financial Data (Revenue, COGS, etc.) you upload. You grant us a limited license to process this data solely to provide the services described in these Terms.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">5. AI Insights and Disclaimer of Liability</h2>
            <p className="text-slate-400 leading-relaxed">The Noble Clarity Engine utilizes cutting-edge AI (Google Gemini 3.0 Flash/OpenAI).</p>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li><strong>No Financial Advice:</strong> The AI Coaching and scenario planning tools provide informational insights only. They do not constitute professional financial, tax, or legal advice.</li>
              <li><strong>Accuracy:</strong> While our Hybrid Intelligence Layer is state-of-the-art, AI-generated content can occasionally contain "hallucinations" or inaccuracies. You must independently verify all AI-generated KPIs and forecasts before making significant business decisions.</li>
              <li><strong>Assumption of Risk:</strong> You assume all risk for business decisions made based on the Platform’s output.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">6. Data Management and the "Wipe Data" Function</h2>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li><strong>Self-Service Deletion:</strong> The Platform provides a "Wipe All Data" function.</li>
              <li><strong>Effect of Deletion:</strong> Activating this feature will trigger the permanent deletion of your profile, financial history, and settings from our Firestore databases and your local storage.</li>
              <li><strong>Irreversibility:</strong> Once triggered, this data cannot be recovered by Noble World support staff. We are not liable for any loss of business records resulting from your use of this feature.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">7. Prohibited Activities</h2>
            <p className="text-slate-400 leading-relaxed">You agree not to:</p>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li>Reverse-engineer or attempt to extract the source code of the Noble Clarity Engine.</li>
              <li>Use the Platform to process data that violates third-party intellectual property or privacy rights.</li>
              <li>Bypass our backend proxy to interact directly with our AI sub-processors (Google/OpenAI).</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">8. Limitation of Liability</h2>
            <p className="text-slate-400 leading-relaxed">To the maximum extent permitted by law, Noble World and its affiliates shall not be liable for any indirect, incidental, or consequential damages, including loss of profits, data, or goodwill, arising from:</p>
            <ul className="list-disc list-inside text-slate-400 space-y-2">
              <li>Your use of the Platform or AI-generated insights.</li>
              <li>Unauthorized access to your account due to weak user credentials.</li>
              <li>Service interruptions caused by third-party providers (Firebase, Google, Paystack).</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">9. Governing Law</h2>
            <p className="text-slate-400 leading-relaxed">
              These Terms are governed by and construed in accordance with the laws of the Federal Republic of Nigeria, without regard to conflict of law principles.
            </p>
          </section>

          <section className="space-y-4 pt-12 border-t border-slate-800">
            <h2 className="text-2xl font-bold">10. Contact Us</h2>
            <p className="text-slate-400">For legal inquiries regarding these Terms:</p>
            <div className="flex items-center gap-3 bg-slate-900 p-6 rounded-2xl border border-slate-800 w-fit">
              <Mail className="text-noble-blue" />
              <a href="mailto:legal@noblesworld.com.ng" className="text-white font-bold hover:text-noble-blue transition-colors">legal@noblesworld.com.ng</a>
            </div>
          </section>
        </div>
      </main>

      <footer className="py-12 border-t border-slate-900 bg-[#0b0e14] text-center text-xs text-slate-600">
        &copy; {new Date().getFullYear()} Noble World | Strategic Compliance
      </footer>
    </div>
  );
};

export default TermsPage;
